import Navbar from "@/components/Navbar";
import { LangProvider } from "@/context/LangContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ProductProvider } from "./api/useProduct";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  trailerCourse,
}: Readonly<{
  children: React.ReactNode;
  trailerCourse: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LangProvider>
          <ProductProvider>
            <Navbar />
            <div className="max-w-7xl justify-between mt-4 mx-auto flex items-start">
              {children}
              {trailerCourse}
            </div>
          </ProductProvider>
        </LangProvider>
      </body>
    </html>
  );
}
